name: ML_projects
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - alembic=1.17.2=py311haa95532_0
  - annotated-types=0.6.0=py311haa95532_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py311haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotlicffi=1.0.9.2=py311h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - catalogue=2.0.10=py311haa95532_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.2.1=py311haa95532_0
  - cloudpathlib=0.21.0=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.10.1=py311haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - confection=0.1.5=py311hbc747e5_0
  - contourpy=1.3.1=py311h214f63a_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.11=py311h885b0b7_0
  - cython-blis=1.0.1=py311h827c3e9_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - geographiclib=2.1=py311haa95532_0
  - geopy=2.4.1=py311haa95532_0
  - greenlet=3.2.4=py311h885b0b7_0
  - holidays=0.83=py311haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=py311haa95532_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - langcodes=3.5.0=py311haa95532_0
  - language-data=1.3.0=py311haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxgboost=2.0.3=h5da7b33_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mako=1.3.10=py311haa95532_0
  - marisa-trie=1.3.1=py311h885b0b7_0
  - markdown-it-py=4.0.0=py311haa95532_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=py311haa95532_0
  - missingno=0.5.2=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - murmurhash=1.0.12=py311h5da7b33_0
  - narwhals=2.7.0=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py311hdb065b2_0
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.4=h725018a_0
  - optuna=4.5.0=py311h51baaa3_0
  - packaging=25.0=py311haa95532_0
  - pandas=2.3.3=py311ha5e6156_0
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.0=py311hbc747e5_0
  - preshed=3.0.9=py311h5da7b33_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py311h3485c13_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=2.0.3=py311haa95532_1
  - pycparser=2.23=py311haa95532_0
  - pydantic=2.12.2=py311haa95532_0
  - pydantic-core=2.41.4=py311h114bc41_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.32.5=py311haa95532_0
  - rich=13.9.4=py311haa95532_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - scikit-learn=1.7.1=py311h3fbe716_0
  - scipy=1.16.0=py311h242c13b_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=80.9.0=py311haa95532_0
  - shellingham=1.5.4=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - smart_open=7.3.1=py311haa95532_0
  - spacy=3.8.2=py311h214f63a_0
  - spacy-legacy=3.0.12=py311haa95532_0
  - spacy-loggers=1.0.4=py311haa95532_0
  - sqlalchemy=2.0.43=py311hda9a48d_0
  - sqlite=3.50.2=hda9a48d_1
  - srsly=2.5.1=py311h5da7b33_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=h59b6b97_0
  - thinc=8.3.2=py311h214f63a_1
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py311h3485c13_1
  - tqdm=4.67.1=py311h746a85d_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.9.0=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing-inspection=0.4.2=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wasabi=1.1.3=py311haa95532_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - weasel=0.4.1=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.14=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - wrapt=1.17.0=py311h827c3e9_0
  - xgboost=2.0.3=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\maria\.conda\envs\ML_projects
